### ISSUE TITLE
LeetCode Problems Solution

### ISSUE THREAD

**Issue by bansalkanav** [bansalkanav/SOLVING_200_LEETCODE_QUESTIONS#19]
Solve a Problem on LeetCode and Submit your solution in C++ or Java or Python3

**Comment by HarshUdai** [comment]
@bansalkanav hey have solved various problems on leet code, can you assign me this

**Comment by bansalkanav** [comment]
Sure @HarshUdai May I know your preferred programming language for contribution?

**Comment by HarshUdai** [comment]
Python is my favourite

**Comment by bansalkanav** [comment]
Cool, assigned. All the best!

**Comment by HarshUdai** [comment]
Hey @bansalkanav i have made a pr please see.
